#!/usr/bin/python

import os, sys

try:
    here = __file__
except NameError:
    here = sys.argv[0]

if os.path.basename(os.path.dirname(here)) == 'scripts':
    # Then we're probably running without having been installed
    # with setup.py...
    sys.path.append(os.path.dirname(os.path.dirname(here)))
    from src import Logo
    from src import tkthread
else:
    from pylogo import Logo
    from pylogo import tkthread

def main(args):
    quit_after = False
    for filename in sys.argv[1:]:
        if filename in ('-q', '--quit'):
            quit_after = True
            continue
        Logo.importLogo(filename)

    if not quit_after:
        Logo.inputLoop(sys.stdin, sys.stdout)

#try:
#    tkthread.start(main, sys.argv[1:])
#finally:
#    tkthread.quit()

main(sys.argv[1:])
